name: build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    env:
      CPG_HOST: ${{ vars.CPG_HOST }}
      CPG_USER: ${{ vars.CPG_USER }}
      CPG_API_CLIENT_ID: ${{ vars.CPG_API_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v2
        with:
          path: pycpg
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox==4.25.0
      - name: Run Unit tests
        run: cd pycpg; tox -e py  # Run tox using the version of Python in `PATH`
      - name: Submit coverage report
        uses: codecov/codecov-action@v1.0.7
        with:
          file: pycpg/coverage.xml
      # - name: Checkout mock servers
      #   uses: actions/checkout@v2
      #   with:
      #     repository: code42/code42-mock-servers
      #     path: code42-mock-servers
      # - name: Add mock servers host addresses
      #   run: |
      #     sudo tee -a /etc/hosts <<EOF
      #     127.0.0.1 localhost
      #     127.0.0.1 core
      #     127.0.0.1 audit-log
      #     127.0.0.1 storage
      #     127.0.0.1 connected-server
      #     EOF
      # - name: Start up the mock servers
      #   run: cd code42-mock-servers; docker compose up -d --build

      - name: Run the integration tests
        run: sleep 15; cd pycpg; tox -e integration
