name: docs

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:

  docs:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
    - name: Install tox
      run: pip install tox==4.25.0
    - name: Build docs
      run: tox -e docs
